export const MOVIE_ACTIONS = {
  FETCHING_MOVIES_IN_PROGRESS: "FETCHING_MOVIES_IN_PROGRESS",
  FETCHING_MOVIES_SUCCESS: "FETCHING_MOVIES_SUCCESS",
  FETCHING_MOVIES_FAILED: "FETCHING_MOVIES_FAILED",
  FETCHING_MOVIE_DETAILS_IN_PROGRESS: "FETCHING_MOVIE_DETAILS_IN_PROGRESS",
  FETCHING_MOVIE_DETAILS_SUCCESS: "FETCHING_MOVIE_DETAILS_SUCCESS",
  FETCHING_MOVIE_DETAILS_FAILED: "FETCHING_MOVIE_DETAILS_FAILED",
};
